// \p{Script=...} and \p{Script_Extensions=...} (and bare script names), from the Unicode 16
// tables in unicode_script.inc (generated by tools/gen_unicode.cpp).
#include "regex/unicode.h"

#include <cctype>
#include <string>

namespace bro::search::rx {

namespace {

struct ScriptTable {
    const char* short_name;
    const char* names[2];  // long name, optional extra alias (Qaai, Qaac)
    const CodepointRange* sc;
    size_t sc_count;
    const CodepointRange* scx_add;  // code points whose Script_Extensions list this script
    size_t scx_add_count;
};

#include "regex/unicode_script.inc"

std::string loose(std::string_view s) {
    std::string out;
    for (char c : s) {
        if (c == ' ' || c == '_' || c == '-') continue;
        out.push_back(static_cast<char>(std::tolower(static_cast<unsigned char>(c))));
    }
    return out;
}

const ScriptTable* find_script(std::string_view raw) {
    const std::string name = loose(raw);
    for (const auto& t : kScripts) {
        if (loose(t.short_name) == name) return &t;
        for (const char* n : t.names)
            if (n && loose(n) == name) return &t;
    }
    return nullptr;
}

} // namespace

bool unicode_script(std::string_view name, bool extensions, CharSet* out) {
    const ScriptTable* t = find_script(name);
    if (!t) return false;
    // Like Rust's regex-syntax (and so rg): Unknown and Katakana_Or_Hiragana are recognised
    // names with no table, so they are errors rather than an empty or complement set.
    if (std::string_view(t->short_name) == "Zzzz" || std::string_view(t->short_name) == "Hrkt")
        return false;
    CharSet s;
    if (t->sc) s.add_table(t->sc, t->sc_count);
    if (extensions) {
        // scx(X) = (sc(X) - code points with an explicit extension list) + those listing X.
        CharSet listed;
        listed.add_table(kScxListed, sizeof(kScxListed) / sizeof(kScxListed[0]));
        listed.canonicalize();
        s.canonicalize();
        s.subtract(listed);
        if (t->scx_add) s.add_table(t->scx_add, t->scx_add_count);
    }
    s.canonicalize();
    *out = s;
    return true;
}

} // namespace bro::search::rx
