// Generates src/fuzzy/fuzzy_unicode_tables.inc: the Unicode data the fzf port needs, matching
// what Go's `unicode` package gives fzf (Go 1.21+ ships Unicode 15.0.0):
//   - character classes for non-ASCII code points (Ll -> lower, Lu -> upper, N* -> number,
//     other L* -> letter, White_Space -> white; everything else is non-word),
//   - simple lowercase mappings (UnicodeData field 13, what unicode.ToLower uses),
//   - fzf's Latin normalization table, parsed from fzf's src/algo/normalize.go.
//
// Usage:
//   gen_fuzzy_unicode <UnicodeData.txt (15.0.0)> <fzf/src/algo/normalize.go> <out.inc>
// UnicodeData.txt: https://www.unicode.org/Public/15.0.0/ucd/UnicodeData.txt

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

namespace {

enum Cls : int { NonWord = 0, White = 1, Lower = 2, Upper = 3, Letter = 4, Number = 5 };

std::vector<std::string> split(const std::string& s, char d) {
    std::vector<std::string> out;
    std::string cur;
    for (char c : s) {
        if (c == d) {
            out.push_back(cur);
            cur.clear();
        } else {
            cur.push_back(c);
        }
    }
    out.push_back(cur);
    return out;
}

int classify(const std::string& gc) {
    if (gc == "Ll") return Lower;
    if (gc == "Lu") return Upper;
    if (!gc.empty() && gc[0] == 'N') return Number;
    if (!gc.empty() && gc[0] == 'L') return Letter;
    return NonWord;
}

} // namespace

int main(int argc, char** argv) {
    if (argc != 4) {
        std::fprintf(stderr, "usage: gen_fuzzy_unicode UnicodeData.txt normalize.go out.inc\n");
        return 2;
    }
    std::vector<uint8_t> cls(0x110000, NonWord);
    std::map<uint32_t, uint32_t> lower;
    {
        std::ifstream in(argv[1]);
        if (!in) {
            std::fprintf(stderr, "cannot open %s\n", argv[1]);
            return 1;
        }
        std::string line;
        uint32_t range_first = 0;
        bool in_range = false;
        while (std::getline(in, line)) {
            if (line.empty()) continue;
            auto f = split(line, ';');
            if (f.size() < 14) continue;
            uint32_t cp = static_cast<uint32_t>(std::stoul(f[0], nullptr, 16));
            int c = classify(f[2]);
            if (f[1].find(", First>") != std::string::npos) {
                range_first = cp;
                in_range = true;
                continue;
            }
            if (in_range && f[1].find(", Last>") != std::string::npos) {
                for (uint32_t x = range_first; x <= cp; ++x) cls[x] = static_cast<uint8_t>(c);
                in_range = false;
                continue;
            }
            cls[cp] = static_cast<uint8_t>(c);
            if (!f[13].empty()) lower[cp] = static_cast<uint32_t>(std::stoul(f[13], nullptr, 16));
        }
    }
    // White_Space (PropList.txt, Unicode 15.0), the set Go's unicode.IsSpace reports.
    for (uint32_t ws : {0x85u, 0xA0u, 0x1680u, 0x2028u, 0x2029u, 0x202Fu, 0x205Fu, 0x3000u}) cls[ws] = White;
    for (uint32_t ws = 0x2000; ws <= 0x200A; ++ws) cls[ws] = White;

    std::vector<std::pair<uint32_t, uint32_t>> norm;
    {
        std::ifstream in(argv[2]);
        if (!in) {
            std::fprintf(stderr, "cannot open %s\n", argv[2]);
            return 1;
        }
        std::string line;
        while (std::getline(in, line)) {
            auto p = line.find("0x");
            auto q = line.find(": '");
            if (p == std::string::npos || q == std::string::npos || p > 2) continue;
            uint32_t key = static_cast<uint32_t>(std::stoul(line.substr(p + 2, q - p - 2), nullptr, 16));
            size_t i = q + 3;
            uint32_t val = static_cast<unsigned char>(line[i]);
            if (line[i] == '\\') val = static_cast<unsigned char>(line[i + 1]);
            norm.emplace_back(key, val);
        }
    }
    std::sort(norm.begin(), norm.end());

    std::ostringstream o;
    o << "// Generated by tools/gen_fuzzy_unicode.cpp from UnicodeData.txt 15.0.0 and fzf's\n"
         "// src/algo/normalize.go (fzf v0.74.4, MIT). Do not edit.\n\n";
    o << "// {first, last, class} for code points >= 0x80; gaps are non-word.\n";
    o << "static constexpr ClassRange kClassRanges[] = {\n";
    int n = 0;
    for (uint32_t cp = 0x80; cp < 0x110000;) {
        uint8_t c = cls[cp];
        uint32_t e = cp;
        while (e + 1 < 0x110000 && cls[e + 1] == c) ++e;
        if (c != NonWord) {
            char buf[64];
            std::snprintf(buf, sizeof buf, "{0x%X,0x%X,%d},", cp, e, c);
            o << buf;
            if (++n % 6 == 0) o << "\n";
        }
        cp = e + 1;
    }
    o << "\n};\n\n// {code point, simple lowercase}\nstatic constexpr CasePair kLowerPairs[] = {\n";
    n = 0;
    for (auto [k, v] : lower) {
        if (k < 0x80) continue;
        char buf[48];
        std::snprintf(buf, sizeof buf, "{0x%X,0x%X},", k, v);
        o << buf;
        if (++n % 8 == 0) o << "\n";
    }
    o << "\n};\n\n// fzf Latin normalization {code point, ASCII}\nstatic constexpr CasePair kNormalizePairs[] = {\n";
    n = 0;
    for (auto [k, v] : norm) {
        char buf[48];
        std::snprintf(buf, sizeof buf, "{0x%X,0x%X},", k, v);
        o << buf;
        if (++n % 8 == 0) o << "\n";
    }
    o << "\n};\n";
    std::ofstream out(argv[3], std::ios::binary);
    out << o.str();
    return out ? 0 : 1;
}
